### ISSUE TITLE
angular 5 support

### ISSUE THREAD

**Issue by snaveenkumareee** [vrudikov/ng4-summernote#1]
can you please provide steps to use this for angular5? I tried updating the references for this module to 5. but on executing, i see the following error.

Uncaught Error: Unexpected module 'SummernoteModule' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.
    at syntaxError (compiler.js:485)
    at eval (compiler.js:15281)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15263)
    at JitCompiler._loadModules (compiler.js:34255)
    at JitCompiler._compileModuleAndComponents (compiler.js:34216)
    at JitCompiler.compileModuleAsync (compiler.js:34110)
    at CompilerImpl.compileModuleAsync (platform-browser-dynamic.js:230)
    at PlatformRef.bootstrapModule (core.js:5568)
    at eval (main.ts:11)
syntaxError @ compiler.js:485
(anonymous) @ compiler.js:15281
CompileMetadataResolver.getNgModuleMetadata @ compiler.js:15263
JitCompiler._loadModules @ compiler.js:34255
JitCompiler._compileModuleAndComponents @ compiler.js:34216
JitCompiler.compileModuleAsync @ compiler.js:34110
CompilerImpl.compileModuleAsync @ platform-browser-dynamic.js:230
PlatformRef.bootstrapModule @ core.js:5568
(anonymous) @ main.ts:11
../../../../../src/main.ts @ main.bundle.js:74
__webpack_require__ @ inline.bundle.js:55
0 @ main.bundle.js:89
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1

Not sure what i am missing.

**Comment by vrudikov** [comment]
@snaveenkumareee hi. i dropped support for this module and switched to angular2-tinymce@^2.1.2. It integrates without pain and have support for modal forms.

**Comment by ali-makhmali** [comment]
Hi @vrudikov ,

I have been trying this as well, and know that you have dropped support for this. But I have a minor problem and would appreciate it if you can help [on this](https://stackoverflow.com/questions/51098208/summernote-angular-5-unable-to-build). Does the tinymce support base64 image?

Thanks.

**Comment by YesidRico** [comment]
### 

> [`****`](

- url

)

**Comment by vrudikov** [comment]
@ali-makhmali Hi. It seems yes. https://stackoverflow.com/questions/29042862/how-do-i-include-base64-image-in-tinymce
